import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AnalyticsInitializer from "./components/AnalyticsInitializer";
import { AnalyticsProvider } from "./providers/AnalyticsProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <AnalyticsInitializer /> */}
        <AnalyticsProvider
          apiKey={process.env.NEXT_PUBLIC_ANALYTICS_API_KEY!}
          batchSize={15} // Send when 15 events queued
          flushInterval={3000} // Flush every 3 seconds
        >
          {children}
        </AnalyticsProvider>
      </body>
    </html>
  );
}
